openapi: 3.0.0
info:
  title: Movie API
  version: 1.0.0
  description: >
    API du service Movie permettant de gérer des films.
    L'accès est protégé par authentification via l'API User
    par un header `X-Token`.
tags:
- name: admin
  description: Secured Admin-only calls
- name: user
  description: Operations available to regular users

servers:
  - url: http://localhost:3001

components:
  securitySchemes:
    TokenAuth:
      type: apiKey
      in: header
      name: X-Token
  schemas:
    Movie:
      type: object
      properties:
        id:
          type: string
          example: 276c79ec-a26a-40a6-b3d3-fb242a5947b6
        title:
          type: string
          example: "The Danish Girl"
        rating:
          type: number
          example: 5.3
        director:
          type: string
          example: "Tom Hooper"
      additionalProperties: true
  responses:
    UnauthorizedError:
      description: Unauthorized - invalid or missing token
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Unauthorized
paths:
  /:
    get:
      summary: home page of the service
      description: |
        Nothing to do
      operationId: home
      responses:
        "200":
          description: welcome message
          content:
            text/html:
              schema:
                type: string
                example: <h1 style='color:blue'>Welcome to the Movie service!</h1>
  /json:
    get:
      tags:
        - admin
      summary: Retourne tous les films
      description: >
        Nécessite les permissions `admin`.  
        Retourne tous les films présents dans MongoDB.
      security:
        - TokenAuth: []
      responses:
        200:
          description: Liste des films
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Movie"
        401:
          $ref: "#/components/responses/UnauthorizedError"

  /movies/{movieid}:
    get:
      tags:
      - user
      summary: Récupère un film par ID
      parameters:
        - in: path
          name: movieid
          required: true
          schema:
            type: string
          description: ID du film
      security:
        - TokenAuth: []
      responses:
        200:
          description: Film correspondant
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Movie"
        401:
          $ref: "#/components/responses/UnauthorizedError"
        500:
          description: Movie ID not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Movie ID not found

    post:
      tags:
        - admin
      summary: Ajoute un film
      description: Nécessite les permissions `admin`.
      parameters:
        - in: path
          name: movieid
          required: true
          schema:
            type: string
      security:
        - TokenAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Movie"
      responses:
        200:
          description: Film ajouté
        401:
          $ref: "#/components/responses/UnauthorizedError"
        500:
          description: Movie ID already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: movie ID already exists

    delete:
      tags:
        - admin
      summary: Supprime un film
      description: Nécessite les permissions `admin`.
      parameters:
        - in: path
          name: movieid
          required: true
          schema:
            type: string
      security:
        - TokenAuth: []
      responses:
        200:
          description: Film supprimé
        401:
          $ref: "#/components/responses/UnauthorizedError"
        500:
          description: Movie ID not found

  /movies/{movieid}/{rate}:
    put:
      tags:
        - admin
      summary: Met à jour la note d’un film
      description: Nécessite les permissions `admin`.
      parameters:
        - in: path
          name: movieid
          required: true
          schema:
            type: string
        - in: path
          name: rate
          required: true
          schema:
            type: string
          description: Nouvelle note du film
      security:
        - TokenAuth: []
      responses:
        200:
          description: Film mis à jour
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Movie"
        401:
          $ref: "#/components/responses/UnauthorizedError"
        500:
          description: Movie ID not found

  /moviesbytitle:
    get:
      tags:
      - user
      summary: Récupère un film via son titre
      parameters:
        - in: query
          name: title
          required: true
          schema:
            type: string
      security:
        - TokenAuth: []
      responses:
        200:
          description: Film correspondant
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Movie"
        401:
          $ref: "#/components/responses/UnauthorizedError"
        500:
          description: movie title not found